/**
 * TechShare Strings Dictionary
 * Centralized strings repository for multi-language and anti-hardcoding standard.
 */

export const STRINGS = {
  COMMON: {
    CONFIRM: 'Confirm',
    CANCEL: 'Cancel',
    OK: 'OK',
    DONE: 'Done',
    LOGOUT: 'Log Out',
    SAVE: 'Save',
    CLOSE: 'Close',
    HOT: 'HOT',
    LOADING: 'Loading...',
    ERROR: 'An error occurred',
    SUCCESS: 'Success',
    RETRY: 'Retry',
    TOTAL: 'Total',
    DATE: 'Date',
    STATUS: 'Status',
    PLEASE_SELECT: 'Please select',
    CURRENCY_SUFFIX: 'VND',
    BULLET_SEPARATOR: '•',
    PEAK_LABEL: 'Peak: ',
    MILLION_SUFFIX: 'M',
    THOUSAND_SUFFIX: 'k',
    ZERO: '0',
  },

  OWNER_DASHBOARD: {
    TOP_BAR_TITLE: 'Owner Dashboard',
    TOP_BAR_SUBTITLE: 'TechShare Owner Hub',
    LOGOUT_MODAL_SUBTITLE: 'Are you sure you want to sign out from TechShare Owner Hub?',
    TRUST_PREFIX: 'Trust: ',
    MENU_ACCESSIBILITY_LABEL: 'Open owner navigation menu',
    NOTIFICATION_ACCESSIBILITY_LABEL: 'View notifications',
    LOGOUT_ACCESSIBILITY_LABEL: 'Sign out',

    // Alert Messages
    DEVICE_RENTED_ALERT_TITLE: 'Device Currently Rented',
    DEVICE_RENTED_ALERT_MSG:
      'This device is actively on rent. You can only modify availability after receiving it back and completing the order.',
    DEVICE_PAUSE_ALERT_TITLE: 'Pause Device Listing',
    DEVICE_PAUSE_ALERT_MSG: (name: string) =>
      `Are you sure you want to pause listing for "${name}"?\n\nRenters will not be able to find or book it until you re-enable it.`,
    DEVICE_AVAILABLE_SUCCESS: 'Device is now available on the rental marketplace.',
    DEVICE_STATUS_UPDATE_ERROR: 'Unable to update device status. Please try again.',

    // Chart Legends & Defaults
    CHART_WEEK_LEGEND: 'Revenue last 7 days (VND)',
    CHART_MONTH_LEGEND: 'Weekly revenue this month (VND)',
    DEFAULT_WEEK_LABELS: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'] as readonly string[],

    // Top Bar tabs info
    TOPBAR_KPI_TITLE: 'KPI & Performance Hub',
    TOPBAR_KPI_SUBTITLE: 'Performance metrics & net revenue',
    TOPBAR_FLEET_TITLE: 'My Device Inventory',
    TOPBAR_FLEET_SUBTITLE: (count: number) => `Manage ${count} devices • Toggle listing`,
    TOPBAR_AI_TITLE: 'AI Smart Assistant',
    TOPBAR_AI_SUBTITLE: 'Dynamic pricing & revenue optimization',

    // Tabs
    TAB_OVERVIEW: 'Performance & Revenue',
    TAB_FLEET: 'Device Fleet',
    TAB_AI_TOOLS: 'AI Tools',

    // Period selector
    PERIOD_WEEK: 'Week',
    PERIOD_MONTH: 'Month',

    // Performance Section
    SECTION_PERFORMANCE: 'Performance & Revenue',
    KPI_NET_REVENUE: 'Net Revenue',
    KPI_RENTAL_COUNT: 'Total Rentals',
    KPI_ACTIVE_RENTALS: 'Active Rentals',
    KPI_OCCUPANCY_RATE: 'Occupancy Rate',
    UNIT_RENTAL_COUNT: 'orders',
    UNIT_DEVICES: 'devices',

    // Wallet Section
    WALLET_AVAILABLE_BALANCE: 'Available Balance',
    WALLET_WITHDRAW_BUTTON: 'Withdraw',
    WALLET_ESCROW_HOLDING: 'Escrow Holding',
    WALLET_MONTHLY_REVENUE: 'Monthly Revenue',
    WALLET_WITHDRAW_ALERT_TITLE: 'Bank Withdrawal Request',
    WALLET_WITHDRAW_ALERT_MSG: (balance: string) =>
      `Current available balance: ${balance}.\nWithdrawal request to linked Vietcombank account (*8899) is being processed in 5-10 minutes.`,

    // Fleet Section
    FLEET_MAIN_TITLE: 'My Device Fleet',
    FLEET_MAIN_SUBTITLE: (count: number) =>
      `Total ${count} devices • Manage availability`,
    FLEET_ADD_DEVICE_BTN: 'Add Device',
    FLEET_ADD_DEVICE_NEW_BTN: 'List New Device',
    FLEET_FILTER_ALL: (count: number) => `All (${count})`,
    FLEET_FILTER_RENTED: (count: number) => `Rented (${count})`,
    FLEET_FILTER_AVAILABLE: (count: number) => `Available (${count})`,
    FLEET_EMPTY_TITLE: 'No matching devices',
    FLEET_EMPTY_RENTED_DESC: 'No devices currently on rent.',
    FLEET_EMPTY_DEFAULT_DESC: 'No devices found in this category.',
    FLEET_STATUS_RENTED: 'Rented',
    FLEET_STATUS_AVAILABLE: 'Available',
    FLEET_STATUS_MAINTENANCE: 'Hidden',
    FLEET_SWITCH_ENABLE: 'Enable Listing',
    FLEET_PRICE_UNIT: 'VND/day',
    FLEET_RENTAL_COUNT_SUFFIX: 'rentals',
    FLEET_TOTAL_EARNED: (amount: string) => `Earned: ${amount}`,
    FLEET_SWITCH_CONFIRM_TITLE: 'Confirm Status Change',
    FLEET_SWITCH_CONFIRM_MSG: (name: string, isAvailable: boolean) =>
      `Are you sure you want to ${isAvailable ? 'hide' : 'make available'} "${name}"?`,
  },

  AI_TOOLS: {
    HEADER_TITLE: 'AI Smart Assistant',
    HEADER_SUBTITLE:
      'Exclusive AI toolset helping owners optimize rental rates, increase occupancy, and auto-generate listings.',

    SMART_PRICING_TITLE: 'AI Dynamic Pricing',
    SMART_PRICING_DESC:
      'Real-time competitive pricing recommendations to maximize total earnings and device utilization.',
    SMART_PRICING_ACTION: 'Analyze Market Rates',
    SMART_PRICING_ALERT_TITLE: 'AI Smart Pricing Assistant',
    SMART_PRICING_ALERT_MSG:
      'Market demand analysis: Sony A7 IV has high demand this weekend. Optimal suggested rate: 480,000 VND/day (+7%).',

    AUTO_LISTING_TITLE: 'AI Listing Copywriter',
    AUTO_LISTING_DESC:
      'Automatically generates catchy titles, rich technical descriptions, and auto-fills spec sheets.',
    AUTO_LISTING_ACTION: 'Create Listing with AI',
    AUTO_LISTING_ALERT_TITLE: 'AI Copywriter',
    AUTO_LISTING_ALERT_MSG: 'Navigate to List Device screen to activate AI drafting.',

    DEMAND_FORECAST_TITLE: 'AI Rental Demand Forecast',
    DEMAND_FORECAST_DESC:
      'Analyzes upcoming holidays and tech events to predict high-demand gadget categories.',
    DEMAND_FORECAST_ACTION: 'View Seasonal Trends',
    DEMAND_FORECAST_ALERT_TITLE: 'AI Demand Forecast',
    DEMAND_FORECAST_ALERT_MSG:
      'Upcoming holiday forecast:\n• Cameras & Gimbals: +42% travel rental demand.\n• Gaming laptops: +28%.\nRecommendation: Keep these devices ready for early bookings.',

    TRUST_REVIEW_TITLE: 'AI Reputation & Review Optimizer',
    TRUST_REVIEW_DESC:
      'Analyzes renter feedback, highlights strengths, and suggests service improvements to maintain Top Owner badge.',
    TRUST_REVIEW_ACTION: 'View Feedback Report',
    TRUST_REVIEW_ALERT_TITLE: 'AI Reputation Optimizer',
    TRUST_REVIEW_ALERT_MSG:
      'Current trust score: 100/100.\n100% 5-star reviews praise: Punctual handover, spotless device, fully charged accessories.',
  },

  ANALYTICS: {
    UTILIZATION_RATE_LABEL: 'Fleet Utilization Rate',
    RENTED_DEVICES_RATIO: (rented: number, total: number) =>
      `${rented} / ${total} devices currently rented`,
    TOTAL_DEVICES: 'Total Devices',
    RENTED_DEVICES: 'Currently Rented',
    AVAILABLE_DEVICES: 'Available',
    TOTAL_REVENUE: 'Cumulative Total Revenue',
    REVENUE_GROWTH_STABLE: 'Steady Growth',
    REVENUE_GROWTH_PCT: (pct: number) => `${pct >= 0 ? '+' : ''}${pct}%`,
    REVENUE_GROWTH_SUB_DEFAULT: 'Net revenue from completed rental orders',
    REVENUE_GROWTH_SUB_COMPARE: 'compared to previous period',
    CHART_DAILY_LABEL: 'Daily Revenue Trend',
    CHART_WEEKLY_LABEL: 'Weekly Revenue Trend',
    RENTER_PREFIX: 'Renter: ',
    STATUS_COMPLETED: 'Completed',
  },

  OWNER_ANALYTICS: {
    TOP_BAR_TITLE: 'Revenue & Analytics',
    TOP_BAR_SUBTITLE: 'Cash flow & rental fleet performance reports',
    MENU_ACCESSIBILITY_LABEL: 'Open owner navigation menu',
    ROLE_REQUIRED_TITLE: 'Owner Access Required',
    ROLE_REQUIRED_SUBTITLE: 'You need to sign in with an Owner account to access analytics.',
    LOADING_TEXT: 'Loading revenue analytics...',
    ERROR_TITLE: 'Unable to Load Analytics',
    SECTION_REVENUE_TREND: 'Revenue Fluctuation',
    SECTION_UTILIZATION: 'Fleet Utilization Performance',
    SECTION_DEVICE_STATS: 'Device Status Breakdown',
    SECTION_PAYMENT_HISTORY: 'Payment History & Statements',
    EMPTY_PAYMENT_TITLE: 'No Payment Transactions Yet',
    EMPTY_PAYMENT_DESC: 'Revenue collected from completed rentals will appear here.',
    WEEKDAYS: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as readonly string[],
    VN_WEEKDAYS: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'] as readonly string[],
  },

  AVAILABILITY: {
    MODAL_TITLE: 'Manage Availability',
    DESCRIPTION: 'Block dates when you need to use this device.',
    MODE_SINGLE: 'Single dates',
    MODE_RANGE: 'Date range',
    PREV_MONTH_ACCESSIBILITY: 'Previous month',
    NEXT_MONTH_ACCESSIBILITY: 'Next month',
    WEEKDAYS: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as readonly string[],
    SELECTED_TITLE: 'Selected blocked dates',
    NO_DATES_SELECTED: 'No blocked dates selected.',
    BLOCKED_DATE_ITEM: (date: string) => `Blocked Date: ${date}`,
    TOTAL_DAYS: (count: number) => `Total: ${count} days`,
    START_DATE: (date: string) => `Start Date: ${date}`,
    END_DATE: (date: string) => `End Date: ${date}`,
    PLEASE_SELECT: 'Please select',
    SAVE_CHANGES: 'Save Changes',
    ALERT_SELECT_RANGE: 'Please select start date and end date',
    ALERT_SELECT_SINGLE: 'Please select at least one date',
    ALERT_SUCCESS_TITLE: 'Success',
    ALERT_SUCCESS_MSG: 'Updated blocked dates successfully.',
    ALERT_ERROR_TITLE: 'Error',
    ALERT_ERROR_MSG: 'Failed to update blocked dates. Please try again.',
    MONTH_NAME: (date: Date) => date.toLocaleString('default', { month: 'long' }),
  },

  ADMIN_SIDEBAR: {
    BRAND_TITLE: 'TechShare Admin',
    BRAND_SUBTITLE: 'Control Center',
    DEFAULT_ADMIN_NAME: 'Administrator',
    DEFAULT_ADMIN_EMAIL: 'admin@techshare.vn',
    ROLE_BADGE: 'System Administrator',
    SECTION_HEADER: 'SYSTEM ADMINISTRATION',
    MENU_OVERVIEW: 'Dashboard & KPIs',
    MENU_USERS: 'User Management',
    MENU_DEVICES: 'Device Moderation',
    MENU_DISPUTES: 'Deposit Disputes',
    MENU_EKYC: 'eKYC Reviews',
    MENU_VOUCHERS: 'Vouchers & Promotions',
    LOGOUT_BUTTON: 'Sign Out of Admin Session',
    LOGOUT_CONFIRM_SUBTITLE: 'Are you sure you want to end this session and sign out of TechShare Admin?',
  },

  OWNER_SIDEBAR: {
    BRAND_TITLE: 'TechShare Owner',
    BRAND_SUBTITLE: 'Owner Operations Portal',
    DEFAULT_OWNER_NAME: 'Owner',
    DEFAULT_OWNER_EMAIL: 'owner@techshare.vn',
    ROLE_BADGE: 'Top Owner',
    TRUST_LABEL: (score: number) => `Trust: ${score}`,
    SECTION_HEADER: 'OWNER MENU',
    MENU_OVERVIEW: 'Dashboard & KPIs',
    MENU_ANALYTICS: 'Revenue & Analytics',
    MENU_ORDERS: 'Pending Bookings',
    MENU_FLEET: 'My Device Inventory',
    MENU_POST_DEVICE: 'List a New Device',
    MENU_WALLET: 'Revenue & Deposit Wallet',
    MENU_AI_TOOLS: 'AI Assistant',
    MENU_RENTER_MODE: 'Switch to Renter Mode',
    MENU_NOTIFICATIONS: 'System Notifications',
    TASKS_SUFFIX: 'tasks',
    NEW_SUFFIX: 'new',
    LOGOUT_BUTTON: 'Sign Out of Owner Session',
    LOGOUT_CONFIRM_TITLE: 'Confirm Sign Out',
    LOGOUT_CONFIRM_SUBTITLE: 'Are you sure you want to end this session and sign out of TechShare Owner?',
  },

  OWNER_NAV: {
    BOOKING_MANAGE_TITLE: 'Booking Management',
    BOOKING_MANAGE_DRAWER: 'Booking Management',
    ANALYTICS_TITLE: 'Owner Analytics',
    ANALYTICS_DRAWER: 'Revenue & Analytics',
    POST_DEVICE_TITLE: 'Post Device',
    POST_DEVICE_DRAWER: 'List New Device',
    NOTIFICATION_TITLE: 'Notification',
    NOTIFICATION_DRAWER: 'System Notifications',
  },

  LOGOUT_MODAL: {
    DEFAULT_TITLE: 'Confirm Sign Out',
    DEFAULT_SUBTITLE: 'Are you sure you want to end this session and sign out of your account?',
    DEFAULT_CONFIRM: 'Log Out',
    DEFAULT_CANCEL: 'Cancel',
    CLOSE_ACCESSIBILITY: 'Close modal',
  },

  DEVICE_STATUS: {
    LABEL_GROUP: 'Device status',
    AVAILABLE: 'Available',
    MAINTENANCE: 'Maintenance',
    HIDDEN: 'Hidden',
  },

  NOTIFICATION_SCREEN: {
    HEADER_TITLE: 'Notifications',
    MENU_ACCESSIBILITY_LABEL: 'Open owner navigation menu',
    BACK_ACCESSIBILITY_LABEL: 'Back',
    MARK_ALL_READ: 'Mark all as read',
    LOADING: 'Loading notifications...',
    EMPTY_TITLE: 'No notifications',
    EMPTY_SUBTITLE_ALL: 'You will receive updates about rental orders and new offers here.',
    EMPTY_SUBTITLE_FILTER: 'No notifications match this filter.',
    DELETE_ACCESSIBILITY_LABEL: 'Delete notification',
    TABS: {
      ALL: 'All',
      ORDER: 'Orders',
      REMINDER: 'Reminders',
      SYSTEM: 'System',
      PROMO: 'Promotions',
    },
    TYPES: {
      ORDER: 'Order',
      REMINDER: 'Reminder',
      PROMO: 'Promotion',
      MESSAGE: 'Message',
      SYSTEM: 'System',
    },
    TIME: {
      JUST_NOW: 'Just now',
      MINUTES_AGO: (mins: number) => `${mins}m ago`,
      HOURS_AGO: (hours: number) => `${hours}h ago`,
      YESTERDAY: 'Yesterday',
      DAYS_AGO: (days: number) => `${days}d ago`,
    },
  },

  MY_DEVICES: {
    TITLE: 'My Devices',
    SUBTITLE: 'Manage your listed devices',
    BACK_ACCESSIBILITY_LABEL: 'Back to Profile',
    LOADING: 'Loading your devices...',
    ERROR_TITLE: 'Unable to load devices',
    ERROR_DEFAULT: 'Cannot load your devices. Please check the server.',
    PRICE_UNIT: ' / day',
    RENTALS_LABEL: 'Rentals',
    RATING_LABEL: 'Rating',
    DEVICE_STATUS_LABEL: 'Device Status',
    MANAGE_AVAILABILITY: 'Manage Availability',
    EMPTY_TITLE: 'No devices yet',
    EMPTY_DESC: "You haven't listed any devices.",
  },

  BOOKING_MANAGE: {
    HEADER_TITLE: 'Booking Management',
    HEADER_SUBTITLE: 'Approve, Handover & Track',
    SCAN_QR: 'Scan QR',
    SEARCH_PLACEHOLDER: 'Search by code, device or renter name...',
    METRIC_PENDING: 'Pending',
    METRIC_ACTIVE: 'Active Rentals',
    METRIC_REVENUE: 'Active Revenue',
    TAB_PENDING: 'Pending',
    TAB_RENTING: 'Active & Renting',
    TAB_HISTORY: 'History',
    LOADING_ORDERS: 'Loading your booking orders...',
    CLEAR_SEARCH: 'Clear search filter',
    EMPTY_PENDING_TITLE: 'No pending bookings',
    EMPTY_RENTING_TITLE: 'No devices currently rented',
    EMPTY_HISTORY_TITLE: 'No order history yet',
    EMPTY_PENDING_SUB: 'All rental requests have been reviewed. When a renter books a device, it will appear here.',
    EMPTY_RENTING_SUB: 'Approved bookings waiting for handover or active ongoing rentals will appear here.',
    EMPTY_HISTORY_SUB: 'Completed, cancelled, or rejected booking records are archived here.',
    CONFIRM_APPROVE_TITLE: 'Confirm Approval 📦',
    CONFIRM_APPROVE_MSG: (code: string, renterName: string) =>
      `Approve booking #${code} for ${renterName}?\n\nInstant confirmation notification will be sent to the renter.`,
    APPROVE_NOW: 'Approve Now',
    APPROVE_SUCCESS_TITLE: 'Approved Successfully! 🎉',
    APPROVE_SUCCESS_MSG: (code: string) =>
      `Booking #${code} is approved. Please prepare the device for handover.`,
    APPROVE_ERROR_DEFAULT: 'Unable to approve booking at this time.',
    HANDOVER_TITLE: 'Device Handover 📱',
    HANDOVER_MSG: (deviceName: string, renterName: string) =>
      `Confirm handover of "${deviceName}" to ${renterName}?\n\nThe booking will activate and the rental period begins now.`,
    CONFIRM_HANDOVER: 'Confirm Handover',
    HANDOVER_SUCCESS_TITLE: 'Handover Successful 🎉',
    HANDOVER_SUCCESS_MSG: (code: string) =>
      `Device handed over. Booking #${code} is now active.`,
    HANDOVER_ERROR_DEFAULT: 'Unable to handover booking at this time.',
    COMPLETE_TITLE: 'Receive Device & Complete 💰',
    COMPLETE_MSG: (deviceName: string, deposit: string, income: string) =>
      `Have you inspected "${deviceName}" and confirmed it is returned in good condition?\n\n• Deposit: ${deposit} VND will be refunded to renter.\n• Earnings: +${income} VND will be credited to your wallet.`,
    CONFIRM_COMPLETE: 'Confirm & Complete',
    RECHECK: 'Recheck',
    COMPLETE_SUCCESS_TITLE: 'Rental Completed 🎉',
    COMPLETE_SUCCESS_MSG: (code: string) =>
      `Booking #${code} is completed. Deposit refunded and earnings credited.`,
    COMPLETE_ERROR_DEFAULT: 'Unable to complete booking at this time.',
    ALREADY_RATED_TITLE: 'Already Rated',
    ALREADY_RATED_MSG: 'You have already rated the renter for this booking.',
    REJECT_MODAL_TITLE: 'Reject Booking Request',
    REJECT_MODAL_DESC: (code: string) =>
      `Select a reason for declining booking #${code}. This reason will be provided to the renter.`,
    REJECT_SUCCESS_TITLE: 'Booking Rejected',
    REJECT_SUCCESS_MSG: (code: string) => `Booking #${code} has been rejected.`,
    REJECT_ERROR_DEFAULT: 'Unable to reject booking at this time.',
    CONFIRM_REJECT: 'Confirm Rejection',
    CUSTOM_REASON_PLACEHOLDER: 'Enter detailed reason for rejection...',
    REJECT_REASONS: [
      'Device under maintenance or unavailable',
      'Unexpected personal scheduling conflict',
      'Inconvenient pickup/handover time or location',
      'Renter unresponsive to verification requests',
      'Other reason',
    ] as readonly string[],
    OTHER_REASON: 'Other reason',
    DEFAULT_RENTER_NAME: 'renter',
    DEFAULT_DEVICE_NAME: 'device',
  },

  REVIEW_MODAL: {
    TITLE: 'Reviews & Feedback',
    ORDER_PREFIX: 'Rental Order #',
    OWNER_PREFIX: 'Owner: ',
    DEFAULT_DEVICE_NAME: 'Device',
    DEFAULT_OWNER_NAME: 'Device Owner',
    INCOMPLETE_ALERT_TITLE: 'Incomplete Review',
    INCOMPLETE_ALERT_MSG: 'Please share your thoughts on the rented device.',
    SUCCESS_ALERT_TITLE: 'Review Submitted! 🎉',
    SUCCESS_ALERT_MSG: 'Thank you for your feedback! Your review helps build a trustworthy TechShare community.',
    ALERT_BUTTON_AWESOME: 'Awesome',
    ERROR_DEFAULT: 'Unable to submit review at this time',
    DEVICE_SECTION_TITLE: '1. Device Quality Rating',
    DEVICE_SECTION_SUBTITLE: 'Performance, appearance, and accuracy compared to description',
    DEVICE_COMMENT_PLACEHOLDER: 'Share detailed feedback about the device (screen, battery, features...)',
    OWNER_SECTION_TITLE: '2. Owner Service Rating',
    OWNER_SECTION_SUBTITLE: 'Hospitality, punctual handover, and technical support',
    OWNER_FEEDBACK_PLACEHOLDER: 'Feedback on owner service attitude and support (optional)...',
    SKIP: 'Skip',
    SUBMIT: 'Submit Review',
    RATING_LABELS: {
      1: 'Very Poor 😡',
      2: 'Poor 🙁',
      3: 'Average 😐',
      4: 'Good 😊',
      5: 'Excellent 🤩',
    } as Record<number, string>,
    OWNER_RATING_LABELS: {
      1: 'Late / Unresponsive',
      2: 'Needs Improvement',
      3: 'On Time',
      4: 'Helpful & Friendly',
      5: 'Outstanding Service ⭐',
    } as Record<number, string>,
    DEVICE_TAGS: [
      'Smooth performance',
      'Like-new condition',
      'Long battery life',
      'Complete accessories',
      'Accurate to description',
    ] as readonly string[],
    OWNER_TAGS: [
      'Very helpful owner',
      'Punctual handover',
      'Great technical support',
      'Quick process',
    ] as readonly string[],
  },

  NOTIFICATION_BANNER: {
    TAG: 'New Notification',
    TIME_JUST_NOW: 'Just now',
  },

  DEVICE_CARD: {
    PRICE_SUFFIX: ' ₫/day',
    DAILY_RATE: 'Daily Rate',
    LOGIN_REQUIRED_TITLE: 'Login Required',
    LOGIN_REQUIRED_MSG: 'Please log in to save devices to your wishlist.',
    STATUS_LABELS: {
      available: 'Available',
      rented: 'Rented',
      maintenance: 'Under Maintenance',
      hidden: 'Unavailable',
    } as Record<string, string>,
    UNAVAILABLE: 'Unavailable',
  },

  WISHLIST: {
    TITLE: 'Wishlist',
    CURRENCY_VND: ' VND',
    PER_DAY: '/day',
    DAILY_RATE: 'Daily Rate',
    AVAILABLE: 'Available',
    RENTED: 'Rented',
    DEFAULT_BRAND: 'TECH',
    EMPTY_TITLE: 'No favorite devices yet',
    EMPTY_SUBTITLE: 'Tap the heart icon on devices you like to save them and view them here!',
    EXPLORE_DEVICES: 'Explore Devices',
    SAVED_COUNT_PREFIX: 'Saved ',
    SAVED_COUNT_SUFFIX: ' devices to wishlist',
    GRID_VIEW: 'Grid view',
    LIST_VIEW: 'List view',
    LOADING: 'Loading wishlist...',
  },

  PROFILE: {
    TITLE: 'Personal profile',
    LOGOUT: 'Log out',
    ROLE_ADMIN: 'Administrator',
    ROLE_OWNER: 'Verified Owner',
    ROLE_RENTER: 'Renter',
    TRUST_SCORE_TITLE: 'Trust Score',
    TRUST_BENEFIT_GOLD: '⭐ Gold tier: 20% deposit discount on rentals',
    TRUST_BENEFIT_SILVER: '✨ Silver tier: Standard deposit rate applied',
    TRUST_BENEFIT_STANDARD: '⚠️ Standard tier: 100% deposit required',
    STAT_DEVICE_RATING: 'Device Rating',
    STAT_OWNER_RATING: 'Owner Rating',
    STAT_TOTAL_REVIEWS: 'Total Reviews',
    LIST_DEVICE_BTN: 'List Your Device',
    IDENTITY_SECTION_TITLE: 'Identity Verification & Trust',
    MY_ACCOUNT_SECTION_TITLE: 'My Account',
    MANAGEMENT_PORTALS_TITLE: 'Management Portals',
    OWNER_DASHBOARD_TITLE: 'Owner Dashboard',
    OWNER_DASHBOARD_DESC: 'Manage devices, revenue & review rental requests',
    ADMIN_PORTAL_TITLE: 'Admin Portal',
    ADMIN_PORTAL_DESC: 'Resolve disputes, review eKYC & monitor platform',
    MY_DEVICES: 'My Devices',
    WISHLIST: 'Wishlist',
    TAB_INFO: 'Info',
    TAB_ADDRESS: 'Address',
    PERSONAL_INFO_TITLE: 'Personal information',
    EDIT: 'Edit',
    SAVE: 'Save',
    FULL_NAME: 'Full name',
    EMAIL: 'Email',
    PHONE_NUMBER: 'Phone number',
    BIO: 'Bio',
    SAVE_CHANGES: 'SAVE CHANGES',
    PICKUP_ADDRESS_TITLE: 'Pickup address',
    STREET_ADDRESS: 'Street address',
    WARD: 'Ward / Commune',
    DISTRICT: 'District',
    CITY: 'City / Province',
    PLACEHOLDER_STREET: 'Enter street address',
    PLACEHOLDER_WARD: 'Enter ward/commune',
    PLACEHOLDER_DISTRICT: 'Enter district',
    PLACEHOLDER_CITY: 'Enter city/province',
    UPDATE_ADDRESS: 'UPDATE ADDRESS',
    TOAST_ADDRESS_REQUIRED_FOR_EKYC: 'Please update your address before verifying eKYC.',
    TOAST_SAVE_INFO_SUCCESS: 'Profile information saved successfully!',
    TOAST_SAVE_INFO_ERROR: 'Unable to save profile information.',
    TOAST_UPDATE_ADDRESS_SUCCESS: 'Default delivery address updated!',
    TOAST_UPDATE_ADDRESS_ERROR: 'Unable to update delivery address.',
    TOAST_AVATAR_SUCCESS: 'Profile photo updated!',
    TOAST_AVATAR_ERROR: 'Unable to update profile photo.',
    TOAST_EKYC_SUBMIT_SUCCESS: 'eKYC application submitted successfully! Administrators will review your documents soon.',
    EKYC: {
      VERIFIED_REAL_USER: 'Verified Real User',
      VERIFIED_OWNER_ID: 'Verified Owner Identity',
      DESC_RENTER_VERIFIED: 'Your identity has been verified. You can now rent devices on TechShare.',
      DESC_OWNER_VERIFIED: 'Account verified with National ID and upgraded to Owner status. You can list devices and carry a Verified Badge.',
      ID_NUMBER_PREFIX: 'ID Number: ',
      PENDING_TITLE: 'eKYC Application Under Review',
      PENDING_DESC: 'Your National ID documents have been submitted to administrators and are being processed.',
      REJECTED_TITLE: 'eKYC Application Rejected',
      REJECTED_REASON_PREFIX: 'Reason: ',
      REJECTED_REASON_DEFAULT: 'ID card photo was blurry or mismatched',
      REJECTED_HINT: '. Please capture clear documents and resubmit.',
      RESUBMIT_BTN: 'Resubmit eKYC Application',
      UNVERIFIED_RENTER_TITLE: 'Real User Verification',
      UNVERIFIED_OWNER_TITLE: 'eKYC Identity Verification',
      BADGE_UNVERIFIED: 'Unverified',
      UNVERIFIED_RENTER_DESC: 'Verify your National ID to confirm identity and enable rental rights.',
      UNVERIFIED_OWNER_DESC: 'Enter National ID number and upload 2 sides of ID card to get a Verified Badge and unlock Owner listing features.',
      TAP_TO_VERIFY: 'Tap to verify now',
    },
  },

  EKYC_MODAL: {
    TITLE: 'Digital Identity Verification (eKYC)',
    SUBTITLE_RENTER: 'Verify real identity to rent equipment',
    SUBTITLE_OWNER: 'Upgrade to Owner & Get Verified Badge',
    ALERT_SUBMIT_SUCCESS_TITLE: 'eKYC Submitted Successfully! 🎉',
    ALERT_SUBMIT_SUCCESS_RENTER: 'Your identity verification request has been submitted to admins for manual review. Once approved, you will be able to rent devices.',
    ALERT_SUBMIT_SUCCESS_OWNER: 'Your identity verification request has been submitted for review. Once approved, your account will receive a Verified Badge and unlock Owner privileges.',
    ERROR_CARD_NUMBER_REQUIRED: 'Please enter your Citizen ID Card (CCCD) number.',
    ERROR_CARD_NUMBER_LENGTH: 'ID Card number must be between 9 and 12 digits.',
    ERROR_ADDRESS_REQUIRED: 'Please enter your residential address.',
    ERROR_ADDRESS_SHORT: 'Address is too short. Please provide detailed street, ward, and district.',
    ERROR_FRONT_REQUIRED: 'Please upload the front photo of your ID card.',
    ERROR_BACK_REQUIRED: 'Please upload the back photo of your ID card.',
    ERROR_DEFAULT_SUBMIT: 'Failed to submit eKYC. Please try again.',
    LABEL_ID_NUMBER: 'Citizen ID (CCCD) Number',
    PLACEHOLDER_ID_NUMBER: 'Enter 9 or 12 digit number...',
    LABEL_ADDRESS: 'Residential Address (matching ID)',
    PLACEHOLDER_ADDRESS: 'Enter detailed street, ward, district, city...',
    LABEL_DOCS: 'ID Card Photos (2 sides)',
    SUBTITLE_DOCS: 'Clear, unblurred photo without flash glare',
    FRONT_TITLE: '1. Front of ID Card',
    BACK_TITLE: '2. Back of ID Card',
    UPLOAD_PHOTO: 'Upload photo',
    RETAKE_PHOTO: 'Retake',
    SUBMIT_BTN: 'Submit Identity Documents',
    NOTICE_FOOTER: 'Your identity documents are securely encrypted and protected following Personal Data Protection regulations.',
    UPLOAD_FRONT_FAILED: 'Unable to upload front ID card photo.',
    UPLOAD_BACK_FAILED: 'Unable to upload back ID card photo.',
    PREV_REJECTED_TITLE: 'Previous submission was rejected',
    REJECT_REASON_PREFIX: (reason: string) => `Reason: ${reason}. Please retake clear photos and resubmit.`,
    ACCOUNT_INFO_TITLE: 'ACCOUNT INFORMATION (AUTO-SYNCED)',
    ACCOUNT_INFO_DESC: 'System automatically syncs details from your account and prevents edits here for verification integrity.',
    FULL_NAME_LABEL: 'Full Name',
    EMAIL_LABEL: 'Email Address',
    PHONE_LABEL: 'Phone Number',
    FIXED_BADGE: 'Fixed',
    NAME_NOT_UPDATED: 'Name not updated',
    EMAIL_NOT_UPDATED: 'Email not updated',
    PHONE_NOT_UPDATED: 'Phone not updated',
    ADDITIONAL_ID_TITLE: 'ADDITIONAL IDENTIFICATION DETAILS',
    ADDITIONAL_ID_DESC: 'Please enter your ID card number and current residential address accurately.',
    NATIONAL_ID_LABEL: 'National ID / CCCD Number *',
    NATIONAL_ID_PLACEHOLDER: 'Enter 9-12 digit ID number (e.g. 079204001234)',
    RESIDENTIAL_ADDRESS_LABEL: 'Residential Address (Permanent / Current) *',
    RESIDENTIAL_ADDRESS_PLACEHOLDER: 'e.g. 123 Nguyen Hue St, Ben Nghe Ward, District 1, Ho Chi Minh City',
    FRONT_HELPER: 'Clearly capture ID number, full name, date of birth, emblem, and portrait photo.',
    BACK_HELPER: 'Clearly capture fingerprints, identifying features, issue date, and MRZ code.',
    CHANGE_PHOTO: 'Change photo',
    UPLOADED_BADGE: 'Uploaded',
    UPLOADING_PHOTO: 'Uploading photo...',
    CAPTURE_FRONT_TEXT: 'Capture or select Front ID Photo',
    CAPTURE_BACK_TEXT: 'Capture or select Back ID Photo',
    FORMAT_HINT: 'JPG, PNG format (max 10MB)',
    POLICY_TITLE: 'Review & Privacy Policy:',
    POLICY_ITEM_1: '• Your eKYC submission will be manually reviewed and matched against official records by TechShare admins.',
    POLICY_ITEM_2_PREFIX: '• Upon successful approval, your account receives a ',
    POLICY_ITEM_2_BADGE: 'Verified Badge',
    POLICY_ITEM_2_MID: ' and unlocks ',
    POLICY_ITEM_2_OWNER: 'Owner',
    POLICY_ITEM_2_SUFFIX: ' capabilities to list equipment.',
    POLICY_ITEM_3: '• ID number and photos are strictly encrypted and used solely for identity verification.',
    SUBMIT_EKYC_BTN: 'SUBMIT eKYC VERIFICATION',
  },

  BOOKING_ITEM_CARD: {
    FROM_PREFIX: 'From: ',
    TO_PREFIX: 'To: ',
    DAYS_UNIT: 'days',
    DAY_UNIT: 'day',
    EXTENSION_PENDING_TAG: (days: number, fee: string) => `Extension pending review: +${days} days (+${fee} VND)`,
    EXTENSION_APPROVED_TAG: (days: number) => `Extension approved (+${days} days)`,
    TOTAL_LABEL: 'Total:',
    CANCEL_BOOKING: 'Cancel Booking',
    EXTENSION_PENDING: 'Extension Pending',
    EXTEND_RENTAL: 'Extend Rental',
    REVIEWED: 'Reviewed',
    RENT_AGAIN: 'Rent Again',
    REVIEW_SERVICE: 'Review Service',
  },

  EXTENSION_MODAL: {
    TITLE: 'Rental Extension Request',
    ORDER_PREFIX: 'Order #',
    REQUEST_SENT_TITLE: 'Request Sent! ⏳',
    REQUEST_SENT_MSG: (days: number) => `Extension request for ${days} day(s) has been forwarded to the owner. You will be notified once reviewed.`,
    GOT_IT: 'Got it',
    FAILED_TITLE: 'Failed',
    FAILED_MSG: 'Unable to send extension request at this time',
    PENDING_TITLE: 'Extension Request Pending Review',
    PENDING_DESC: (days: number) => `You have requested to extend by ${days} day(s). Please wait for the owner to respond before submitting a new request.`,
    SECTION_LABEL: 'Select number of days to extend:',
    DAYS_UNIT: 'days',
    DAYS_CHIP: (days: number) => `+${days} days`,
    CURRENT_RETURN_LABEL: 'Current return date:',
    NEW_RETURN_LABEL: 'New estimated return date:',
    DAILY_RATE_LABEL: 'Daily rate:',
    RATE_UNIT: 'VND/day',
    ADDITIONAL_FEE_LABEL: 'Additional extension fee:',
    FEE_PREFIX: '+',
    NOTICE_TEXT: '💡 Extension requests are sent directly to the device owner. The return schedule and rental fees will be updated once approved.',
    SKIP: 'Skip',
    CONFIRM: 'Confirm Extension Request',
  },

  HANDOVER_QR: {
    TITLE: 'Handover QR Code',
    SUBTITLE: 'Present when receiving the device',
    STATUS_READY: 'Ready for Handover Verification',
    BOOKING_CODE_LABEL: 'Booking Code:',
    DEVICE_LABEL: 'Device:',
    DURATION_LABEL: 'Duration:',
    DURATION_DAYS: (days: number) => `${days} days`,
    ALERT_TITLE: 'Booking Code',
    ALERT_TOKEN_PREFIX: 'Verification Token: ',
    HINT_TEXT: 'Show this QR code to the owner to scan and verify upon in-person handover.',
    CLOSE: 'Close',
  },

  HANDOVER_CAMERA: {
    TITLE: 'Capture Handover Record',
    SUBTITLE: 'Take photos of 4 angles and condition notes',
    SLOT_FRONT_TITLE: '1. Front View',
    SLOT_FRONT_SUB: 'Clear screen, top & bottom bezels',
    SLOT_BACK_TITLE: '2. Back View',
    SLOT_BACK_SUB: 'Back cover, camera bump, logo',
    SLOT_EDGES_TITLE: '3. Edges & Corners',
    SLOT_EDGES_SUB: 'Frame, charging port, buttons',
    SLOT_ACC_TITLE: '4. Accessories & Box',
    SLOT_ACC_SUB: 'Charger, cable, case, accessories...',
    PICK_ALERT_TITLE: 'Capture Handover Photos',
    PICK_ALERT_MSG: 'Choose photo capture method for this angle:',
    TAKE_PHOTO_BTN: 'Take Photo 📸',
    CHOOSE_LIBRARY_BTN: 'Choose from Library 🖼️',
    PERMISSION_ALERT_TITLE: 'Camera Permission',
    PERMISSION_ALERT_MSG: 'Please grant camera permission to take device photos.',
    PERMISSION_LIB_MSG: 'Please grant photo library access.',
    SUCCESS_ALERT_TITLE: 'Saved! 🎉',
    SUCCESS_ALERT_MSG: 'Handover photos and condition notes recorded successfully.',
    ERROR_ALERT_TITLE: 'Error',
    ERROR_ALERT_MSG: 'Unable to save handover photos',
    NOTES_LABEL: 'Device Condition Notes upon Handover:',
    NOTES_PLACEHOLDER: 'Describe physical condition, existing scratches, battery percentage, included accessories...',
    CANCEL: 'Cancel',
    CONFIRM_SAVE: 'Save Handover Photos',
    MISSING_PHOTOS_TITLE: 'Missing Photos',
    MISSING_PHOTOS_MSG: 'Please capture at least 1 device photo upon handover.',
    CAPTURED_LABEL: (taken: number, total: number) => `Captured: ${taken}/${total} angles`,
    ADVICE_TEXT: 'Handover photos are critical evidence to cross-check upon return (after rental), ensuring transparent deposit resolution.',
    SKIP: 'Skip',
    SAVE_RECORD_BTN: 'Save Handover Record',
    TAKE_PHOTO_BADGE: 'Take Photo',
  },

  RENTAL_COUNTDOWN: {
    REMAINING_TITLE: 'Remaining Rental Time',
    OVERDUE_TITLE: 'Rental Overdue',
    URGENT_TITLE: 'Urgent: Return within 2 hours',
    WARNING_TITLE: 'Expiring soon (< 6h)',
    OVERDUE_BADGE: 'OVERDUE',
    DAYS: 'Days',
    HOURS: 'Hours',
    MINS: 'Mins',
    SECS: 'Secs',
    COMPACT_REMAINING_PREFIX: 'Remaining: ',
    COMPACT_OVERDUE_PREFIX: 'Overdue: ',
  },

  MY_BOOKINGS: {
    TITLE: 'My Bookings',
    TABS: {
      ALL: 'All',
      PENDING: 'Pending',
      APPROVED: 'Approved',
      ACTIVE: 'Active',
      COMPLETED: 'Completed',
      CANCELLED: 'Cancelled',
    },
    CANCEL_REASONS: [
      'Changed mind, no longer need rental',
      'Found a better alternative',
      'Schedule no longer works',
      'Other reason',
    ] as readonly string[],
    ALERT_CANCEL_SELECT_REASON: 'Please select or enter a cancellation reason',
    ALERT_CANCEL_SUCCESS: 'Booking cancelled successfully',
    ALERT_CANCEL_ERROR_DEFAULT: 'Unable to cancel booking at this time',
    EMPTY_TITLE: 'No Bookings Yet',
    EMPTY_DESC: 'You do not have any device bookings in this status.',
    EXPLORE_DEVICES: 'Explore Devices',
    CANCEL_MODAL_DESC: (code: string) => `You are requesting to cancel order #${code}. Please provide a reason:`,
    REASON_PLACEHOLDER: 'Or enter another reason...',
  },

  BOOKING_CREATE: {
    TITLE: 'Book Rental Device',
    TOTAL_PAYMENT: 'Total payment',
    CONFIRM_BOOKING: 'Confirm Booking',
    DELIVERY_ADDRESS_LABEL: 'Delivery address',
    DELIVERY_ADDRESS_PLACEHOLDER: 'Enter street address, building, ward/commune, district...',
    PICKUP_TIME_TITLE: 'Pickup Date & Time',
    RETURN_TIME_TITLE: 'Return Date & Time',
    PICKUP_TIME_SUB: 'Choose date & time you wish to receive the device',
    RETURN_TIME_SUB: 'Choose date & time you will return the device',
    SELECTED_DATE: 'Selected Date',
    SELECTED_TIME: 'Selected Time',
    DATE_UNAVAILABLE_TITLE: 'Date Unavailable',
    DATE_UNAVAILABLE_MSG: 'The device is already booked on this date. Please select another available date on the calendar!',
    ALREADY_BOOKED: 'Already Booked',
    TIME_SUGGESTIONS: 'Time suggestions:',
    HOUR: 'Hour',
    MINUTE: 'Minute',
    INVALID_TIME_TITLE: 'Invalid Time',
    PAST_TIME_MSG: 'Pickup time cannot be in the past.',
    RETURN_BEFORE_PICKUP_MSG: 'Return time must be after pickup time.',
    DATES_UNAVAILABLE_TITLE: 'Dates Unavailable',
    SCHEDULE_CONFLICT_TITLE: 'Schedule Conflict',
    DELIVERY_METHOD_TITLE: 'Handover Method',
    METHOD_PICKUP: 'Self Pickup',
    METHOD_DELIVERY: 'Doorstep Delivery',
    PICKUP_ADDRESS_LABEL: 'Pickup location:',
    MISSING_INFO_TITLE: 'Missing Information',
    MISSING_DATES_MSG: 'Please select pickup and return dates/times.',
    MISSING_DELIVERY_ADDRESS_MSG: 'Please enter a delivery address for the owner to ship the device.',
    DEVICE_RENTED_TITLE: 'Device Currently Rented',
    SUCCESS_TITLE: 'Success',
    SUCCESS_MSG: 'Booking request submitted successfully!',
    CONFIRM_BTN: 'Confirm',
    CANCEL_BTN: 'Cancel',
  },

  BOOKING_DETAIL: {
    TITLE: 'Booking Details',
    LOADING: 'Loading booking details...',
    NOT_FOUND: 'Booking details not found.',
    GO_BACK: 'Go Back',
    DEVICE_INFO: 'Device Information',
    VIEW_DEVICE_DETAILS: 'View Device Details',
    RENTAL_PERIOD: 'Rental Period',
    PICKUP: 'PICKUP',
    RETURN: 'RETURN',
    DEVICE_OWNER: 'Device Owner',
    CALL: 'Call',
    EMAIL: 'Email',
    PAYMENT_DETAILS: 'Payment Details',
    RENTAL_FEE: 'Rental fee',
    SECURITY_DEPOSIT: 'Security deposit (refundable upon return):',
    DISCOUNT_VOUCHER: 'Discount voucher',
    TOTAL_AMOUNT: 'Total amount:',
    PAYMENT_STATUS: 'Payment status:',
    HANDOVER_METHOD: 'Handover Method',
    DOORSTEP_DELIVERY: 'Doorstep delivery',
    SELF_PICKUP: 'Self pickup at designated location',
    ADDRESS_PREFIX: 'Address: ',
    CONTACT_OWNER: 'Contact owner directly',
    HANDOVER_RECORD: 'Handover Record (before rental)',
    PHOTOS_COUNT: (count: number) => `${count}/4 photos`,
    PHOTOS_DESC: '4-angle photos taken at handover (used for comparison upon return):',
    ANGLE_PREFIX: 'Angle ',
    CONDITION_NOTES: 'Condition notes:',
    UPDATE_RETAKE_PHOTOS: 'Update / Retake handover photos',
    NO_PHOTOS_TITLE: 'No handover photos saved yet',
    NO_PHOTOS_DESC: 'Capture all 4 angles and accessories when receiving the device to protect your deposit.',
    TAKE_PHOTOS_CTA: 'Take Handover Photos (4 angles)',
    SHOW_QR_CTA: 'Show Handover QR Code',
    CANCEL_BOOKING: 'Cancel Booking',
    CONFIRM_CANCEL_TITLE: 'Confirm Cancellation',
    CONFIRM_CANCEL_MSG: (code: string) => `Are you sure you want to cancel booking #${code}?`,
    KEEP_BOOKING: 'Keep Booking',
    CONFIRM_CANCEL_ACTION: 'Confirm Cancel',
    CANCEL_SUCCESS: 'Booking cancelled.',
    CANCEL_ERROR: 'Unable to cancel booking',
    HANDOVER_QR_BTN: 'Handover QR Code',
    TAKE_PHOTOS_BTN: 'Take Photos',
    EXTEND_RENTAL: 'Extend Rental',
    EXTENSION_PENDING: 'Extension Pending',
    RENT_AGAIN: 'Rent this device again',
    ALERT_ERROR_TITLE: 'Error',
    ALERT_SUCCESS_TITLE: 'Success',
    LOAD_ERROR_MSG: 'Unable to load booking details',
    ALERT_NOTICE_TITLE: 'Notice',
    OWNER_PHONE_NA: 'Owner phone number not available.',
    OWNER_EMAIL_NA: 'Owner email not available.',
    EXTENSION_PENDING_TITLE: 'Extension Request Pending Review',
    EXTENSION_PENDING_DESC: (days: number, fee: number, date: string) =>
      `Extend +${days} days (+${fee.toLocaleString('en-US')} VND). New expected return: ${date}.`,
    EXTENSION_APPROVED_TITLE: (days: number) => `Extension approved (+${days} days)`,
    REVIEW_QUALITY_BTN: 'Review Service Quality',
    DAY_UNIT: (count: number) => (count === 1 ? 'day' : 'days'),
    VND_PER_DAY: 'VND/day',
    CANCEL_REASON_DEFAULT: 'Customer requested cancellation via details screen',
    DEFAULT_DEVICE_NAME: 'Device',
    DEFAULT_CATEGORY: 'Technology',
    DEFAULT_OWNER_NAME: 'TechShare Owner',
    REVIEWS_SUFFIX: (count: number) => `(${count} reviews)`,
    PHONE_PREFIX: 'Phone: ',
    STATUS: {
      pending: 'Pending',
      approved: 'Approved',
      active: 'Active',
      completed: 'Completed',
      cancelled: 'Cancelled',
      rejected: 'Rejected',
    } as Record<string, string>,
    PAYMENT_STATUS_LABELS: {
      unpaid: 'Unpaid',
      deposit_held: 'Deposit Held (Escrow)',
      paid: 'Paid',
      refunded: 'Refunded',
      disputed: 'Disputed',
    } as Record<string, string>,
  },

  PRICE_BREAKDOWN: {
    TITLE: 'Payment Breakdown',
    BASE_RENTAL: (days: number) => `Base rental (${days} ${days === 1 ? 'day' : 'days'})`,
    LONG_TERM_DISCOUNT: (pct: number) => `Long-term discount (${pct}%)`,
    DISCOUNT_VOUCHER: 'Discount voucher',
    SECURITY_DEPOSIT: 'Security deposit (refundable)',
    TOTAL_PAYMENT: 'Total payment',
  },

  VOUCHER_INPUT: {
    TITLE: 'Discount Voucher',
    APPLIED_LABEL: 'Applied voucher: ',
    PLACEHOLDER: 'Enter voucher code (e.g. SALE20)',
    APPLY: 'Apply',
    VALIDATE_ERROR: 'Unable to validate voucher code',
  },

  DEVICE_DETAIL: {
    LOGIN_REQUIRED_TITLE: 'Login Required',
    LOGIN_REQUIRED_MSG: 'Please log in to save devices to your wishlist.',
    AI_ERROR_TITLE: 'Error',
    AI_BUSY_MSG: 'AI is currently busy. Please try again later.',
    AI_ERROR_MSG: 'Unable to analyze this device. Please try again.',
    NOT_FOUND: 'Device not found',
    INVALID_ID: 'Invalid device ID',
    LOAD_ERROR: 'Unable to load device',
    LOADING: 'Loading device details...',
    TRY_AGAIN: 'Try Again',
    BACK: 'Back',
    IMAGE_UNAVAILABLE: 'Image unavailable',
    NO_IMAGE_AVAILABLE: 'No image available',
    REVIEWS_SUFFIX: (count: number) => `(${count} reviews)`,
    DAILY_RENTAL_PRICE: 'Daily rental price',
    SECURITY_DEPOSIT: 'Security deposit',
    DEVICE_INFO: 'Device Information',
    BRAND: 'Brand',
    CONDITION: 'Condition',
    OWNER: 'Owner',
    DESCRIPTION: 'Description',
    SPECIFICATIONS: 'Specifications',
    AI_REVIEW_BTN: 'AI Review',
    AI_ANALYZING_BTN: 'Analyzing...',
    TOTAL_RENTAL_FEE: 'Total rental fee',
    PER_DAY: '/day',
    BOOK_NOW: 'Book Now',
    BOOK_DEVICE_FALLBACK: (title: string) => `Book device: ${title}`,
    NOT_SPECIFIED: 'Not specified',
    CONDITION_LABELS: {
      new: 'New',
      new99: 'Like New',
      used: 'Used',
      used95: 'Gently Used',
      good: 'Good',
      fair: 'Fair',
      scratched: 'Visible Wear',
    } as Record<string, string>,
    STATUS_LABELS: {
      available: 'Available',
      rented: 'Currently Rented',
      maintenance: 'Under Maintenance',
      hidden: 'Unavailable',
    } as Record<string, string>,
    SPEC_LABELS: {
      'màn hình': 'Display',
      pin: 'Battery',
      'bộ nhớ': 'Storage',
      'vi xử lý': 'Chip',
      'hệ điều hành': 'Operating System',
      'kích thước': 'Dimensions',
      'trọng lượng': 'Weight',
    } as Record<string, string>,
  },

  POST_DEVICE: {
    DISCARD_TITLE: 'Discard listing?',
    DISCARD_MSG: 'The information you entered will be lost if you leave now.',
    STAY: 'Stay',
    DISCARD: 'Discard',
    HEADER_TITLE: 'List New Device',
    HEADER_SUBTITLE: 'Publish your tech device for rent',
    ACCESSIBILITY_MENU: 'Open owner management menu',
    ACCESSIBILITY_BACK: 'Go back',
    ACCESSIBILITY_HELP: 'Help',
    LOCATION_DENIED: 'Location permission denied.',
    LOCATION_ENABLE: 'Please enable location services and try again.',
    LOCATION_ERROR: 'Could not get your location.',
    LOCATION_GETTING: 'Getting location...',
    LOCATION_CAPTURED_BTN: 'Location captured — update',
    LOCATION_USE_CURRENT: 'Use Current Location',
    LOCATION_SUCCESS: 'Location captured successfully.',
    LOCATION_HELPER: 'Capture your location to set the device’s map position.',
    DEVICES_LOAD_ERROR: 'Cannot load your devices. Please check the server.',
    ERR_ADDRESS_REQUIRED: 'Please enter the device address.',
    ERR_LOCATION_REQUIRED: 'Please use current location before publishing.',
    ERR_NUMERIC_PRICE_DEPOSIT: 'Price and deposit must be valid numbers.',
    ERR_LOGIN_REQUIRED: 'Please log in before publishing a device.',
    ERR_ADD_PHOTO: 'Please add at least one device image.',
    ERR_ADD_VALID_PHOTO: 'Please add at least one valid device image.',
    ERR_UPLOAD_IMAGE: 'Could not upload device image.',
    ERR_DEVICE_CREATION: 'Images uploaded, but device creation failed.',
    SUCCESS_PUBLISHED_TITLE: 'Listing published',
    SUCCESS_PUBLISHED_MSG: 'Your device is now ready for renters to discover.',
    DONE: 'Done',
    ERR_PUBLISH_DEFAULT: 'Could not publish this device. Please try again.',
    INTRO_TITLE: 'List your device',
    INTRO_TEXT: 'Share your technology with others and earn by renting it out.',
    YOUR_DEVICES_TITLE: 'Your devices',
    YOUR_DEVICES_DESC: 'Devices you have already listed for rent.',
    LOADING_DEVICES: 'Loading your devices...',
    NO_DEVICES_YET: 'You have not listed any device yet.',
    SECTION_PHOTOS: 'Device Photos',
    REMOVE_PHOTO: 'Remove photo',
    ADD_PHOTOS_TITLE: 'Add device photos',
    ADD_PHOTOS_HINT: 'Clear photos help renters know what they are getting.',
    SECTION_DEVICE_INFO: 'Device Information',
    LABEL_DEVICE_NAME: 'Device Name',
    PLACEHOLDER_DEVICE_NAME: 'e.g. iPhone 15 Pro Max 256GB',
    ERR_NAME_REQUIRED: 'Device name is required',
    LABEL_CATEGORY: 'Category',
    SELECT_CATEGORY: 'Select a category',
    LABEL_BRAND: 'Brand',
    PLACEHOLDER_BRAND: 'e.g. Apple',
    ERR_BRAND_REQUIRED: 'Brand is required',
    LABEL_ADDRESS: 'Display Address',
    PLACEHOLDER_ADDRESS: 'e.g. 123 Nguyen Trai, Thanh Xuan, Hanoi',
    ERR_ADDRESS_FIELD: 'Display address is required',
    LABEL_LOCATION: 'Location',
    SECTION_PRICING: 'Rental Pricing',
    LABEL_RENTAL_PRICE: 'Rental Price / Day',
    PLACEHOLDER_PRICE: 'Enter daily rental price',
    ERR_PRICE_REQUIRED: 'Rental price is required',
    LABEL_DEPOSIT: 'Security Deposit',
    PLACEHOLDER_DEPOSIT: 'Enter security deposit',
    ERR_DEPOSIT_REQUIRED: 'Security deposit is required',
    DEPOSIT_HELPER: 'The deposit protects the owner against potential damage or loss.',
    SECTION_DESCRIPTION: 'Description',
    PLACEHOLDER_DESCRIPTION: 'Describe the device condition, included accessories, and anything renters should know...',
    ERR_DESCRIPTION_REQUIRED: 'Description is required',
    SECTION_SPECS: 'Technical Specifications',
    SECTION_SPECS_DESC: 'Add important technical details that help renters understand the device.',
    BTN_PUBLISHING: 'Publishing...',
    BTN_PUBLISH: 'Publish Listing',
    BTN_DRAFT_SAVED: 'Draft Saved',
    BTN_SAVE_DRAFT: 'Save Draft',
    DRAFT_SAVED_MSG: 'Your draft has been saved on this device.',
    ERR_COMPLETE_SPECS: 'Please complete all technical specifications.',
    CURRENCY_VND: 'VND',
    PER_DAY_SUFFIX: 'VND/day',
    STATUS_AVAILABLE: 'Available',
    SPECS_FORM: {
      TITLE: 'Technical Specifications',
      DESC: 'Add specifications that describe this device.',
      EMPTY_TITLE: 'No specifications added yet.',
      EMPTY_DESC: 'Add technical details to help renters understand your device.',
      SPEC_NUMBER_PREFIX: 'SPECIFICATION ',
      DELETE_ACCESSIBILITY: 'Delete specification',
      LABEL_SPEC: 'Specification',
      LABEL_VALUE: 'Value',
      PLACEHOLDER_SPEC: 'e.g. Storage',
      PLACEHOLDER_VALUE: 'e.g. 256GB',
      ERR_ENTER_BOTH: 'Please enter both a specification and value.',
      BTN_ADD: 'Add Specification',
    },
  },

  AUTH_VERIFY_ALERT: {
    TITLE: 'Identity Verification Required',
    MSG: 'You must complete Identity Verification (eKYC) before renting a device.',
    LATER: 'Later',
    VERIFY_NOW: 'Verify Now',
  },

  ADMIN: {
    DASHBOARD: {
      CONFIRM_DELETE_TITLE: 'Confirm Device Removal',
      CONFIRM_DELETE_MSG: (name: string) => `Are you sure you want to remove "${name}" from the marketplace?\n\nThe listing will be hidden and marked as deleted (isDeleted: true).`,
      CANCEL: 'Cancel',
      REMOVE_DEVICE: 'Remove Device',
      DELETE_SUCCESS_TITLE: 'Device Removed',
      DELETE_SUCCESS_MSG: (name: string) => `Device "${name}" has been removed successfully.`,
      DELETE_ERROR: 'Unable to delete device.',
      TAB_TITLES: {
        disputes: 'Dispute Resolution',
        ekyc: 'eKYC Reviews',
        devices: 'Device Moderation',
        users: 'User Management',
        vouchers: 'Vouchers & Promotions',
        default: 'TechShare Admin Hub',
      },
      MENU_ACCESSIBILITY: 'Open admin menu',
      EXIT: 'Exit',
      LOADING: 'Loading TechShare Admin data...',
    },
    EKYC_MODAL: {
      SELFIE_LABEL: '3. Portrait Photo (Selfie)',
      REJECT_REASON_LABEL: 'Rejection reason (sent to user):',
      REJECT_PLACEHOLDER: 'e.g. ID card front photo is blurry, please retake...',
      CONFIRM_REJECT: 'Confirm Application Rejection',
      REJECT: 'Reject',
      VERIFY_IDENTITY: 'Verify Identity',
      APPROVE_BADGE: 'Approve & Grant Badge',
      BACK: 'Back',
    },
    DISPUTE_MODAL: {
      CONFIRM_TITLE: 'Confirm Arbitration Ruling',
      CONFIRM_MSG: (code: string, deduct: string, refund: string) =>
        `Are you sure you want to resolve the dispute for order #${code}?\n\n• Owner compensation: ${deduct} VND\n• Renter refund: ${refund} VND\n\nEscrow funds will be transferred immediately.`,
      CANCEL: 'Cancel',
      EXECUTE_RULING: 'Execute Ruling',
      SUCCESS_TITLE: 'Success! 🎉',
      SUCCESS_MSG: 'Arbitration ruling issued and escrow funds transferred successfully.',
      ERROR_DEFAULT: 'Unable to resolve dispute.',
      MODAL_TITLE: 'Arbitrate Deposit Dispute',
      ORDER_PREFIX: (code: string, device: string) => `Order #${code} • ${device}`,
      OWNER_ROLE: 'Owner (Claimant)',
      RENTER_ROLE: 'Renter',
      TOTAL_ESCROW_LABEL: 'Total Escrow Deposit Held',
      OWNER_CLAIMED_LABEL: 'Owner Claimed Deduction',
      CLAIM_DETAILS_LABEL: 'Claim details from Owner:',
      INSPECTION_HEADING: '📸 BEFORE & AFTER RENTAL PHOTO INSPECTION',
      PRE_HANDOVER_TITLE: 'Pre-handover Photo',
      RETURN_EVIDENCE_TITLE: 'Return & Evidence Photo',
      INTACT_BADGE: 'Intact at pickup',
      DAMAGE_BADGE: 'Damage after use',
      RULING_HEADING: '⚖️ ADMINISTRATOR RULING',
      CHOICE_PARTIAL_TITLE: 'Partial deposit deduction (Compensate Owner)',
      CHOICE_PARTIAL_DESC: 'Owner receives repair compensation, remaining deposit is refunded to renter.',
      CHOICE_PARTIAL_INPUT_LABEL: 'Enter deduction amount for owner compensation (VND):',
      CHOICE_PARTIAL_PLACEHOLDER: 'Enter amount (e.g. 1500000)',
      OWNER_COMPENSATION_LABEL: 'Owner compensation:',
      RENTER_REFUND_LABEL: 'Renter refund:',
      CHOICE_REFUND_TITLE: 'Full 100% Refund to Renter',
      CHOICE_REFUND_DESC: (fee: string) =>
        `Insufficient evidence or standard wear and tear. Renter receives full ${fee} VND.`,
      CHOICE_DEDUCT_TITLE: 'Full 100% Deduction to Owner',
      CHOICE_DEDUCT_DESC: (fee: string) =>
        `Severe damage or lost accessories. Owner receives full ${fee} VND.`,
      REPORT_NOTE_LABEL: 'Ruling report notes (optional):',
      REPORT_NOTE_PLACEHOLDER: 'Specify the reason for the ruling to notify both parties...',
      CLOSE: 'Close',
      SUBMIT_RULING: 'Issue Arbitration Ruling',
    },
    OVERVIEW_TAB: {
      SECTION_PLATFORM_PERF: 'Platform Performance Overview',
      KPI_GROSS_REVENUE: 'Gross Rental Volume',
      KPI_REVENUE_GROWTH: '+18.4% this month',
      KPI_USERS: 'Users',
      KPI_USERS_COUNT: (count: number) => `${count} Accounts`,
      KPI_USERS_SUB: (verified: number) => `${verified} Verified • 11 Active`,
      KPI_DEVICES: 'Total Devices',
      KPI_DEVICES_COUNT: (count: number) => `${count} Units`,
      KPI_DEVICES_SUB: (rented: number, available: number) => `${rented} Rented • ${available} Available`,
      KPI_ORDERS: 'Rental Orders',
      KPI_ORDERS_COUNT: (count: number) => `${count} Orders`,
      KPI_ORDERS_SUB: (active: number, completed: number) => `${active} Active • ${completed} Completed`,
      SECTION_ACTION_ITEMS: 'Action Items',
      PENDING_PILL: (count: number) => `${count} pending`,
      EMPTY_TASKS: 'System operating smoothly • No pending disputes or verification requests',
      DISPUTE_CARD_TITLE: (code: string) => `Deposit Dispute: Order #${code}`,
      URGENT_BADGE: 'Urgent',
      DISPUTE_DEFAULT_DESC: 'Owner requested deposit deduction due to scratched metal frame.',
      DISPUTE_ACTION_LINK: 'Review photos & arbitrate deposit →',
      EKYC_CARD_TITLE: (count: number) => `${count} eKYC verification requests pending review`,
      PENDING_BADGE: 'Pending',
      EKYC_CARD_DESC_SUFFIX: ' submitted ID document and portrait selfie.',
      EKYC_ACTION_LINK: 'Verify documents & approve badge →',
      SECTION_CATEGORY_BREAKDOWN: 'Rental Category Breakdown',
      CAT_CAMERAS: 'Cameras & Lenses',
      CAT_LAPTOPS: 'Graphic Laptops',
      CAT_SMARTPHONES: 'Smartphones',
      CAT_GAMING: 'Gaming & Drones',
    },
    DEVICES_TAB: {
      TITLE: (count: number) => `Device Moderation (${count})`,
      SEARCH_PLACEHOLDER: 'Search by device name or brand...',
      CATEGORIES: {
        all: 'All',
        camera: 'Cameras',
        laptop: 'Laptops',
        smartphone: 'Smartphones',
        drone: 'Drones',
        gaming: 'Gaming',
      } as Record<string, string>,
      EMPTY_TITLE: 'No devices found',
      EMPTY_DESC: 'Try searching with different keywords.',
      BRAND_CONDITION: (brand: string, condition: string) => `Brand: ${brand} • Condition: ${condition}`,
      PRICE_DEPOSIT: (price: string, deposit: string) => `${price} VND/day • Deposit: ${deposit} VND`,
      REMOVE_FLAG_BTN: 'Remove / Flag Device',
    },
    DISPUTES_TAB: {
      TITLE: (count: number) => `Deposit Disputes (${count})`,
      EMPTY_TITLE: 'No Disputes Found',
      EMPTY_DESC: 'Platform operations are running smoothly with no active deposit claims.',
      STATUS_RESOLVED: 'Resolved',
      STATUS_PENDING: 'Pending Ruling',
      DEFAULT_DEVICE: 'Tech Device',
      CLAIMANT_LABEL: 'Claimant (Owner):',
      DEFAULT_OWNER: 'Owner',
      RENTER_LABEL: 'Renter:',
      DEFAULT_RENTER: 'Renter',
      ESCROW_DEPOSIT_LABEL: 'Escrow Deposit:',
      CLAIMED_DEDUCTION_LABEL: 'Claimed Deduction:',
      REASON_PREFIX: (reason: string) => `Reason: "${reason}"`,
      REVIEW_ARBITRATE_BTN: 'Review Photos & Arbitrate Deposit',
      RULING_NOTICE: (decision: string, amount: string) => `Ruling: ${decision} (Deducted ${amount} VND)`,
    },
    EKYC_TAB: {
      TITLE: (count: number) => `eKYC Verification Requests (${count})`,
      EMPTY_TITLE: 'No Verification Requests',
      EMPTY_DESC: 'There are currently no pending verification requests.',
      DEFAULT_USER: 'User',
      BADGE_VERIFIED_RENTER: 'Verified Renter',
      BADGE_VERIFIED_OWNER: 'Verified Owner',
      BADGE_REJECTED: 'Rejected',
      NO_EMAIL: 'No email',
      NOT_UPDATED: 'Not updated',
      META_SUB: (email: string, phone: string) => `${email} • Phone: ${phone}`,
      REQ_RENTER: 'Request: Renter Identity Verification',
      REQ_OWNER: 'Request: Owner eKYC Verification',
      ID_CARD_NO_LABEL: 'ID Card No: ',
      ADDRESS_LABEL: 'Address: ',
      THUMB_FRONT: 'ID Card Front',
      THUMB_BACK: 'ID Card Back',
      THUMB_SELFIE: 'Portrait Selfie',
      MANUAL_REVIEW_NOTICE: 'Manual Review • Verify identity details and 2-sided ID card',
      BTN_REVIEW_RENTER: 'Review & Verify Identity',
      BTN_REVIEW_OWNER: 'Review Documents & Grant Badge',
      STATUS_APPROVED_RENTER: 'Identity verified; account retains renter role with rental eligibility.',
      STATUS_APPROVED_OWNER: 'Documents approved; verified badge granted.',
      STATUS_REJECTED: (reason: string) => `Application rejected. Reason: ${reason}`,
      DEFAULT_REJECT_REASON: 'Invalid',
    },
    USERS_TAB: {
      TITLE: (count: number) => `User Accounts (${count})`,
      INVALID_SESSION: 'Invalid session. Please log in again.',
      LOAD_ERROR: 'Unable to load user list. Please try again.',
      REASON_REQUIRED_TITLE: 'Reason Required',
      REASON_REQUIRED_MSG: 'Please enter a reason for suspending this account.',
      LOCK_SUCCESS_TITLE: 'Success',
      LOCK_SUCCESS_MSG: 'Account suspended and reason recorded.',
      LOCK_ERROR_TITLE: 'Error',
      LOCK_ERROR_MSG: 'Unable to suspend account. Please try again.',
      UNLOCK_CONFIRM_TITLE: 'Confirm Unlock Account',
      UNLOCK_CONFIRM_MSG: (name: string) => `Are you sure you want to unlock account "${name}"?`,
      UNLOCK_SUCCESS_MSG: 'Account unlocked successfully.',
      UNLOCK_ERROR_MSG: 'Unable to unlock account. Please try again.',
      SEARCH_PLACEHOLDER: 'Search by name, email, phone number...',
      ROLE_CHIPS: {
        all: 'All',
        renter: 'Renter',
        owner: 'Owner',
        admin: 'Admin',
      } as Record<string, string>,
      LOADING_USERS: 'Loading user data...',
      EMPTY_TITLE: 'No users found',
      EMPTY_DESC: 'Try searching with different keywords.',
      LOAD_FAIL_TITLE: 'Unable to load data',
      RETRY: 'Retry',
      PHONE_LABEL: 'Phone: ',
      TRUST_SCORE_LABEL: 'Trust Score:',
      RENTALS_LABEL: 'Rentals:',
      ORDERS_SUFFIX: 'orders',
      STATUS_LABEL: 'Status:',
      STATUS_ACTIVE: 'Active',
      STATUS_SUSPENDED: 'Suspended',
      SUSPENSION_REASON_LABEL: 'Suspension reason: ',
      BTN_SUSPEND: 'Suspend Account',
      BTN_UNLOCK: 'Unlock Account',
      MODAL_TITLE: 'Suspend Account',
      MODAL_DESC: (name: string) => `Enter a reason for suspending ${name}.`,
      MODAL_DEFAULT_USER: 'this user',
      MODAL_PLACEHOLDER: 'Enter suspension reason...',
      MODAL_CANCEL: 'Cancel',
      MODAL_CONFIRM: 'Suspend Account',
    },
    VOUCHERS_TAB: {
      TITLE: (count: number) => `Promo Vouchers (${count})`,
      CREATE_CODE_BTN: 'Create Code',
      LOADING_TEXT: 'Loading vouchers list...',
      EMPTY_TITLE: 'No vouchers available',
      EMPTY_SUBTITLE: 'Tap "Create Code" to add a new voucher',
      STATUS_ACTIVE: 'Active',
      STATUS_PAUSED: 'Paused',
      LABEL_DISCOUNT: 'Discount:',
      LABEL_MIN_RENTAL: 'Min Rental:',
      DAYS_SUFFIX: 'days',
      LABEL_USED: 'Used:',
      MAX_DISCOUNT_NOTE: (amount: string) => `Max discount: ${amount} VND`,
      EXPIRES_LABEL: (date: string) => `Expires: ${date}`,
      ACTION_PAUSE: 'Pause',
      ACTION_ACTIVATE: 'Activate',
      DELETE_CONFIRM_TITLE: 'Confirm Deletion',
      DELETE_CONFIRM_MSG: (code: string) => `Are you sure you want to delete voucher "${code}"?`,
      DELETE_SUCCESS_MSG: (code: string) => `Deleted voucher "${code}"`,
      DELETE_ERROR_MSG: 'Unable to delete voucher',
      STATUS_UPDATE_ERROR: 'Unable to update voucher status',
      ERR_CODE_REQUIRED: 'Please enter a voucher code',
      ERR_VALUE_INVALID: 'Please enter a valid discount value',
      SAVE_SUCCESS_UPDATE: 'Voucher updated successfully',
      SAVE_SUCCESS_CREATE: 'New voucher created successfully',
      SAVE_ERROR_DEFAULT: 'Unable to save voucher',
      MODAL_TITLE_EDIT: 'Edit Voucher',
      MODAL_TITLE_CREATE: 'Create New Voucher',
      LABEL_CODE: 'Voucher Code *',
      PLACEHOLDER_CODE: 'e.g. SUMMER2026',
      LABEL_DISCOUNT_TYPE: 'Discount Type *',
      TYPE_PERCENT: 'Percentage (%)',
      TYPE_FIXED: 'Fixed Amount (VND)',
      LABEL_DISCOUNT_VALUE: (type: string) => `Discount Value (${type}) *`,
      PLACEHOLDER_PERCENT: 'e.g. 10',
      PLACEHOLDER_FIXED: 'e.g. 50000',
      LABEL_MAX_DISCOUNT: 'Max Discount (VND)',
      PLACEHOLDER_MAX_DISCOUNT: 'e.g. 100000',
      LABEL_MIN_DAYS: 'Min Rental (days)',
      PLACEHOLDER_MIN_DAYS: 'e.g. 1',
      LABEL_USAGE_LIMIT: 'Usage Limit',
      PLACEHOLDER_USAGE_LIMIT: 'Leave empty = Unlimited',
      LABEL_PER_USER_LIMIT: 'Per User Limit',
      PLACEHOLDER_PER_USER: 'e.g. 1',
      LABEL_EXPIRY_DATE: 'Expiry Date (YYYY-MM-DD)',
      PLACEHOLDER_EXPIRY_DATE: 'e.g. 2026-12-31',
      LABEL_ACTIVATE_NOW: 'Activate Immediately',
      BTN_CANCEL: 'Cancel',
      BTN_DELETE: 'Delete',
      BTN_UPDATE: 'Update',
      BTN_CREATE: 'Create',
    },
  },

  OWNER_APPROVAL_CARD: {
    STATUS: {
      pending: 'Pending Approval',
      approved: 'Approved • Ready to Handover',
      active: 'Active • Rental in Progress',
      completed: 'Completed',
      rejected: 'Rejected',
      cancelled: 'Cancelled by Renter',
    } as Record<string, string>,
    DAYS_UNIT: 'days',
    DEFAULT_DEVICE_TITLE: 'Tech Device',
    DEFAULT_RENTER_NAME: 'Renter',
    RENT_LABEL: (amount: string) => `Rent: ${amount} VND`,
    DEPOSIT_LABEL: (amount: string) => `Deposit: ${amount} VND`,
    VERIFIED_BADGE: 'Verified',
    TRUST_SCORE_LABEL: (score: number) => `5.0 • Trust score: ${score}`,
    DELIVERY_PREFIX: (address: string) => `Delivery: ${address}`,
    DELIVERY_DEFAULT_ADDR: 'Renter designated address',
    PICKUP_LABEL: 'Self pick-up at owner location',
    BEFORE_RENTAL_PHOTOS: (count: number) => `Saved ${count}/4 condition verification photos`,
    REJECTION_REASON_PREFIX: 'Rejection reason: ',
    REJECTION_REASON_DEFAULT: 'Owner unavailable',
    CANCELLATION_REASON_PREFIX: 'Cancellation reason: ',
    CANCELLATION_REASON_DEFAULT: 'Cancelled by renter',
    COMPLETED_BANNER: 'Rental completed • Deposit refunded to renter • Earnings added to wallet',
    RATED_RENTER_TITLE: 'Rated Renter Trust:',
    STARS_SUFFIX: (rating: number) => `${rating}/5 stars`,
    RATE_CTA_TITLE: 'Rate Renter Responsibility',
    RATE_CTA_SUB: 'Credit or debit renter trust score',
    RATE_NOW_BTN: 'Rate Now',
    REJECT_BTN: 'Reject',
    APPROVE_BTN: 'Approve Booking',
    SCAN_QR_BTN: 'Scan Handover QR',
    MANUAL_ACTIVATE_BTN: 'Manual Activate',
    RECEIVE_COMPLETE_BTN: 'Receive Device & Complete',
  },

  OWNER_RATE_RENTER_MODAL: {
    TITLE: 'Rate Renter Responsibility',
    SUBTITLE: "This feedback impacts the renter's trust score",
    DEFAULT_DEVICE: 'Device',
    DEFAULT_RENTER: 'Renter',
    CURRENT_TRUST: (score: number) => `Current trust score: ${score}/100`,
    SECTION_RATING_LEVEL: 'Select Rating Level:',
    SECTION_QUICK_TAGS: 'Quick Tags:',
    SECTION_COMMENTS: 'Additional Comments (optional):',
    COMMENTS_PLACEHOLDER: 'Leave specific notes regarding device handling, care, or return...',
    SKIP_BTN: 'Skip',
    SUBMIT_BTN: (stars: number) => `Submit Rating (${stars} ★)`,
    ERR_NOT_FOUND: 'Unable to find booking details for this review.',
    ERR_SUBMIT: 'Unable to submit rating at this time.',
    SUCCESS_TITLE: 'Rating Submitted ✅',
    SUCCESS_MSG: (stars: number, delta: string) => `${stars}-star rating recorded.\n${delta} will update immediately on the renter's profile.`,
    LEVELS: {
      1: { label: 'Terrible', desc: 'Severe violation, serious device damage, or missing essential accessories' },
      2: { label: 'Poor', desc: 'Dirty condition, minor scratches, returned late without prior notice' },
      3: { label: 'Fair', desc: 'Slightly late return with prior communication, device in acceptable condition' },
      4: { label: 'Good', desc: 'Well maintained, polite communication, returned punctually on time' },
      5: { label: 'Excellent', desc: 'Exemplary renter, immaculate condition, all accessories complete, returned early' },
    } as Record<number, { label: string; desc: string }>,
    QUICK_TAGS: [
      { label: '✓ Clean & pristine condition', good: true },
      { label: '✓ Returned on time', good: true },
      { label: '✓ Polite & respectful communication', good: true },
      { label: '✓ All accessories complete', good: true },
      { label: '⚠️ Late return', good: false },
      { label: '⚠️ Stains / minor scratches', good: false },
      { label: '⚠️ Missing included accessories', good: false },
      { label: '⚠️ Unresponsive / difficult communication', good: false },
    ] as readonly { label: string; good: boolean }[],
    DELTA_INFO: {
      5: '+ 2 Trust Points',
      4: '+ 1 Trust Point',
      3: 'No Change',
      2: '− 5 Trust Points',
      1: '− 10 Trust Points',
    } as Record<number, string>,
  },

  OWNER_QR_SCANNER: {
    ERR_INVALID_TOKEN: 'Booking not found or invalid QR token. Please check the code.',
    ERR_VERIFY_DEFAULT: 'Unable to verify QR token. Please check and try again.',
    ALERT_REQUIRED_TITLE: 'Required',
    ALERT_REQUIRED_MSG: 'Please enter a booking code or QR verification token.',
    SUCCESS_TITLE: 'Handover Successful! 🎉',
    SUCCESS_MSG: (code: string) => `Booking #${code} is now ACTIVE. Rental timer has started.`,
    ERR_HANDOVER_TITLE: 'Handover Error',
    ERR_HANDOVER_DEFAULT: 'Failed to activate handover. Please try again.',
    HEADER_TITLE: 'Scan Handover QR',
    HEADER_SUBTITLE: 'Verify & activate device rental',
    TAB_CAMERA: 'Camera Scanner',
    TAB_MANUAL: 'Manual Input',
    BADGE_VALID_QR: 'Valid Handover QR Verified',
    LABEL_BOOKING_CODE: 'Booking Code',
    DEFAULT_DEVICE: 'Tech Device',
    RENTAL_DURATION: (days: number) => `Rental duration: ${days} days`,
    TOTAL_LABEL: (amount: string) => `Total: ${amount} VND`,
    SECTION_RENTER_INFO: 'Renter Information',
    DEFAULT_RENTER_NAME: 'Renter',
    PHONE_LABEL: 'Phone: ',
    NOT_PROVIDED: 'Not provided',
    PHOTOS_TITLE: 'Before-Rental Device Photos (4 angles)',
    PHOTOS_DESC_UPLOADED: (count: number) => `Renter uploaded ${count}/4 condition verification photos.`,
    PHOTOS_DESC_NONE: 'No photos taken yet. Renter can take photos upon receipt.',
    BTN_CONFIRM_HANDOVER: 'Confirm Handover & Activate',
    ALREADY_ACTIVE_TEXT: 'This rental is ALREADY ACTIVE and in progress.',
    OTHER_STATUS_TEXT: (status: string) => `Current status: ${status}. Handover is only available for Approved orders.`,
    BTN_SCAN_ANOTHER: 'Scan Another Code',
    PERMISSION_TITLE: 'Camera Permission Required',
    PERMISSION_DESC: 'We need your permission to access the camera to scan handover QR codes.',
    BTN_GRANT_CAMERA: 'Grant Camera Access',
    BTN_USE_MANUAL: 'Use Manual Input Instead',
    VERIFYING_TEXT: 'Verifying code...',
    TARGET_PROMPT: "Align the renter's QR code within the frame",
    MANUAL_TITLE: 'Enter Handover Code',
    MANUAL_DESC: "Type the booking code (e.g. #TS123456) or the handover token provided on the renter's screen.",
    MANUAL_PLACEHOLDER: 'e.g. TS123456 or TSQR-...',
    BTN_VERIFY_MANUAL: 'Verify & Inspect Booking',
    ERR_VERIFICATION_FAILED: 'Verification Failed',
  },
} as const;


